---
- name: ontap
  hosts: localhost 
  collections:
    - netapp.ontap
  gather_facts: false
  tasks:
  - name: Create FlexVol
    na_ontap_volume:
      state: present
      name: ansibleVolume01
      vserver: poc_svm
      aggregate_name: netapp1
      size: 1
      size_unit: gb
      space_guarantee: none
      hostname: 121.126.207.110
      username: admin
      password: netapp123!
      https: true
      validate_certs: false
